spin_version = "1"
name = "stats-tracker-ghcr"
version = "0.0.1"
trigger = { type = "http", base = "/" }

[[component]]
files = [
  { source = "lib", destination = "/lib" },
  { source = ".gem", destination = "/.gem" },
  { source = "3_2-wasm32-unknown-wasi-full/usr", destination = "/usr" },
]
id = "ruby"
source = "3_2-wasm32-unknown-wasi-full/usr/local/bin/ruby"
[component.trigger]
executor = { type = "wagi", argv = "${SCRIPT_NAME} -v /lib/test.rb ${SCRIPT_NAME} ${ARGS}" }
route = "/"
[component.environment]
HOME = "/"
GEM_HOME = "/.gem"
