apiVersion: v1
kind: Service
metadata:
  labels:
    app: stats-viewer
  name: stats-viewer
spec:
  type: ClusterIP
  selector:
    app: stats-viewer
  ports:
  - name: http
    port: 80
    targetPort: 3000
