---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "projects.example.com"
spec:
  group: "example.com"
  names:
    plural: "projects"
    singular: "project"
    kind: "Project"
    shortNames:
    - proj
  scope: "Namespaced"
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Status
      type: string
    name: "v1alpha1"
    schema:
      openAPIV3Schema:
        required: ["spec"]
        properties:
          spec:
            required: ["projectName"]
            properties:
              projectName:
                type: "string"
                minimum: 1
            type: object
          status:
            properties:
              count:
                type: "string"
                minimum: 1
              lastUpdate:
                type: "string"
                minimum: 1
              conditions:
                description: Conditions holds the conditions for the Project
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              lastHandledReconcileAt:
                description: LastHandledReconcileAt holds the value of the most recent
                  reconcile request value, so a change of the annotation value can
                  be detected.
                type: string
              observedGeneration:
                description: ObservedGeneration is the last observed generation of
                  the Project object.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "leaves.example.com"
spec:
  group: "example.com"
  names:
    plural: "leaves"
    singular: "leaf"
    kind: "Leaf"
    shortNames:
    - l
  scope: "Namespaced"
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Status
      type: string
    name: "v1alpha1"
    schema:
      openAPIV3Schema:
        required: ["spec"]
        properties:
          spec:
            required: ["repoName", "projectName", "packageName"]
            properties:
              repoName:
                type: "string"
                minimum: 1
              projectName:
                type: "string"
                minimum: 1
              packageName:
                type: "string"
                minimum: 1
            type: object
          status:
            properties:
              count:
                type: "string"
                minimum: 1
              lastUpdate:
                type: "string"
                minimum: 1
              conditions:
                description: Conditions holds the conditions for the Leaf
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              lastHandledReconcileAt:
                description: LastHandledReconcileAt holds the value of the most recent
                  reconcile request value, so a change of the annotation value can
                  be detected.
                type: string
              observedGeneration:
                description: ObservedGeneration is the last observed generation of
                  the Leaf object.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "packageversions.example.com"
spec:
  group: "example.com"
  names:
    plural: "packageversions"
    singular: "packageversion"
    kind: "PackageVersion"
    shortNames:
    - pkv
  scope: "Namespaced"
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Status
      type: string
    name: "v1alpha1"
    schema:
      openAPIV3Schema:
        required: ["spec"]
        properties:
          spec:
            required: ["projectName", "packageName"]
            properties:
              projectName:
                type: "string"
                minimum: 1
              packageName:
                type: "string"
                minimum: 1
            type: object
          status:
            properties:
              count:
                type: "string"
                minimum: 1
              lastUpdate:
                type: "string"
                minimum: 1
              conditions:
                description: Conditions holds the conditions for the PackageVersion
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              lastHandledReconcileAt:
                description: LastHandledReconcileAt holds the value of the most recent
                  reconcile request value, so a change of the annotation value can
                  be detected.
                type: string
              observedGeneration:
                description: ObservedGeneration is the last observed generation of
                  the PackageVersion object.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
# ---
# apiVersion: "apiextensions.k8s.io/v1"
# kind: "CustomResourceDefinition"
# metadata:
#   name: "versionleaves.example.com"
# spec:
#   group: "example.com"
#   names:
#     plural: "versionleaves"
#     singular: "versionleaf"
#     kind: "VersionLeaf"
#     shortNames:
#     - vl
#   scope: "Namespaced"
#   versions:
#   - additionalPrinterColumns:
#     - jsonPath: .metadata.creationTimestamp
#       name: Age
#       type: date
#     - jsonPath: .status.conditions[?(@.type=="Ready")].status
#       name: Ready
#       type: string
#     - jsonPath: .status.conditions[?(@.type=="Ready")].message
#       name: Status
#       type: string
#     name: "v1alpha1"
#     schema:
#       openAPIV3Schema:
#         required: ["spec"]
#         properties:
#           spec:
#             required: ["projectName", "packageName", "version"]
#             properties:
#               projectName:
#                 type: "string"
#                 minimum: 1
#               packageName:
#                 type: "string"
#                 minimum: 1
#               version:
#                 type: "string"
#                 minimum: 1
#             type: object
#           status:
#             properties:
#               count:
#                 type: "string"
#                 minimum: 1
#               lastUpdate:
#                 type: "string"
#                 minimum: 1
#               conditions:
#                 description: Conditions holds the conditions for the VersionLeaf
#                 items:
#                   properties:
#                     lastTransitionTime:
#                       format: date-time
#                       type: string
#                     message:
#                       description: message is a human readable message indicating
#                         details about the transition. This may be an empty string.
#                       maxLength: 32768
#                       type: string
#                     observedGeneration:
#                       description: observedGeneration represents the .metadata.generation
#                         that the condition was set based upon.
#                       format: int64
#                       minimum: 0
#                       type: integer
#                     reason:
#                       description: reason contains a programmatic identifier
#                       maxLength: 1024
#                       minLength: 1
#                       pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
#                       type: string
#                     status:
#                       description: status of the condition, one of True, False, Unknown.
#                       enum:
#                       - "True"
#                       - "False"
#                       - Unknown
#                       type: string
#                     type:
#                       maxLength: 316
#                       pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
#                       type: string
#                   required:
#                   - lastTransitionTime
#                   - message
#                   - reason
#                   - status
#                   - type
#                   type: object
#                 type: array
#               lastHandledReconcileAt:
#                 description: LastHandledReconcileAt holds the value of the most recent
#                   reconcile request value, so a change of the annotation value can
#                   be detected.
#                 type: string
#               observedGeneration:
#                 description: ObservedGeneration is the last observed generation of
#                   the VersionLeaf object.
#                 format: int64
#                 type: integer
#             type: object
#         type: object
#     served: true
#     storage: true
#     subresources:
#       status: {}
